Merge Scribbles to main
Project-MONAI/MONAILabel pull request #249
Opened 2021-07-26 16:19 UTC by SachidanandAlle

2021-08-05 19:03 UTC, aihsani requested changes

2021-08-05 19:18 UTC, SachidanandAlle commented on monailabel/interfaces/tasks/postproc.py
> +        return []
Agreed.. just create a PostProcTask

2021-08-05 19:22 UTC, SachidanandAlle commented on sample-apps/segmentation_spleen_postproc/main.py
> +            "BIFSeg+CRF": SpleenBIFSegCRF(),
create a postproc task (similar to infer, strategy, scoring etc..) and init the same.. then u don't need this additional short-cut in your app to capture the logits etc..

2021-08-06 14:16 UTC, SachidanandAlle commented on monailabel/interfaces/tasks/postproc.py
> +        return self.run_transforms(data, self.postproc(), log_prefix="PROC")
removed this file.. lets not have a confusion for postproc.. like deepedit/deepgrow we will have a model/infer for scribbles.. rest all logic will be same as infer.. for inference user can hook any callable methods

2021-08-06 14:19 UTC, SachidanandAlle commented on sample-apps/segmentation_spleen_postproc/main.py
> +            "BIFSeg+CRF": SpleenBIFSegCRF(),
Now scribbles is a model which has pre/infer/post actions inside.. there is no more postproc kind

2021-08-06 14:31 UTC, aihsani approved these changes

2021-08-06 15:02 UTC, merged