Fix static path endpoints
Project-MONAI/MONAILabel pull request #419
Opened 2021-09-23 22:46 UTC by diazandr3s

Signed-off-by: Andres <diazandr3s@gmail.com>
- Static files broken

2021-09-23 22:54 UTC, diazandr3s commented
This PR should fix the problem @masadcv

2021-09-23 23:04 UTC, masadcv commented
Thanks for looking into this and fixing it @diazandr3s !

2021-09-23 23:04 UTC, masadcv approved these changes

2021-09-24 12:30 UTC, aihsani requested changes

2021-09-24 12:30 UTC, aihsani commented on monailabel/main.py
> +    StaticFiles(directory=os.path.join(project_root_absolute, "monailabel/endpoints/static")),
I think you can use
```
os.path.join(project_root_absolute, "monailabel", "endpoints", "static")
```
to be OS agnostic.

2021-09-24 13:30 UTC, aihsani approved these changes

2021-09-24 13:44 UTC, merged