croppad deepedit transforms
Project-MONAI/MONAILabel pull request #530
Opened 2021-11-16 20:13 UTC by pritesh-mehta

I have added two transforms, which are an alternative to ResizeGuidanceCustomd, for DeepEdit pipelines that choose to crop/pad images to a certain size for CNN processing, rather than downsampling/upsampling.

Use case: Prostate segmentation. In my application, I crop the input image as pre-processing to remove background tissues, so need to adjust the guidance in line with crop.

2021-11-16 22:05 UTC, diazandr3s approved these changes

2021-11-16 22:54 UTC, SachidanandAlle requested changes
How about the impact? Is it going to impact current App?
How about unit tests if it's a new code?

2021-11-16 23:06 UTC, diazandr3s commented
> How about the impact? Is it going to impact current App? How about unit tests if it's a new code?

These are very good points. 
These transforms will potentially increase clicks interaction for the deepedit.

I agree we should also include unit tests for these transforms. Happy to help with that :)

2021-11-18 18:19 UTC, pritesh-mehta commented
Unit tests added for new transforms. Please review.

2021-11-18 18:42 UTC, SachidanandAlle approved these changes

2021-11-18 18:42 UTC, merged